In [1]:
import numpy as np

<h1>Create numpay arrays</h1>

In [3]:
newarr=np.array([1,2,3,4,5])

In [4]:
print(newarr)

[1 2 3 4 5]


In [5]:
np.array([3.14,4,3,2]) #all elements are considered of the same type

array([3.14, 4.  , 3.  , 2.  ])

In [6]:
np.array([1,2,3,4],dtype='float32') # to explicitly set the data type

array([1., 2., 3., 4.], dtype=float32)

<h2> from scratch</h2>

In [7]:
#crate a length-10 integer array filled with zeros
np.zeros((10,3), dtype=int)

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

In [9]:
#crate a length-10 integer array filled with 1s
np.ones((3,5),dtype=float)

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [10]:
#crate a 3*5 array filled with 2.74
np.full((3,5),2.74)

array([[2.74, 2.74, 2.74, 2.74, 2.74],
       [2.74, 2.74, 2.74, 2.74, 2.74],
       [2.74, 2.74, 2.74, 2.74, 2.74]])

In [11]:
np.arange(0,10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [12]:
np.arange(0,20,2) # stepping by 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18])

In [15]:
#crate a 3*3 array 
#random values between 0 and 1
np.random.random((3,3))

array([[0.21790969, 0.79685067, 0.36401803],
       [0.85991691, 0.55923823, 0.42811943],
       [0.43441985, 0.03829841, 0.31723858]])

In [9]:
np.random.randint(0,100,(3,3))

array([[80, 53, 49],
       [90, 61, 69],
       [37, 35, 46]])

In [11]:
np.emty((3,5))

array([[0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0.]])

<h2> NumPy Array Attributes</h2>


In [13]:
x=np.zeros((3,4,5))

In [14]:
x

array([[[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]],

       [[0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.],
        [0., 0., 0., 0., 0.]]])

In [18]:
print("x ndim:", x.ndim) #عدد الابعاد
print("x shape:", x.shape)
print("x size:", x.size) # 3*4*5


x ndim: 3
x shape: (3, 4, 5)
x size: 60


<h2>Array Indexing</h2>

In [3]:
x= np.arange(10)
x


array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
x[1:5]


array([1, 2, 3, 4])

In [22]:
x[:5]

array([0, 1, 2, 3, 4])

In [5]:
x[::2]


array([0, 2, 4, 6, 8])

In [24]:
x[1::2]

array([1, 3, 5, 7, 9])

In [25]:
x[::-1]

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

In [6]:
x2 = np.array([[12,5,2,4],[7,6,8,8],[1,6,7,7]])
x2

array([[12,  5,  2,  4],
       [ 7,  6,  8,  8],
       [ 1,  6,  7,  7]])

<h2> Multidimensional sumarrays</h2>

In [7]:
x2[0:2, 2:3]

array([[2],
       [8]])

In [8]:
x2[1:2 ,1:3]

array([[6, 8]])

In [11]:
x2[:3 ,::2]

array([[12,  2],
       [ 7,  8],
       [ 1,  7]])

In [12]:
x2[1:,3:]

array([[8],
       [7]])

In [14]:
x2[::-1,::-1]

array([[ 7,  7,  6,  1],
       [ 8,  8,  6,  7],
       [ 4,  2,  5, 12]])

In [15]:
x2[:,0] # first column

array([12,  7,  1])

In [16]:
x2[0,:] # first row

array([12,  5,  2,  4])